title: Interdisciplinary Livestock Microbiome Research Lab
email: a.rahman@umanitoba.ca
description: >
  A research group focused on livestock microbiomes and host-microbe interactions.
baseurl: "" 
url: "https://zisanurrahman.github.io"

theme: minima

markdown: kramdown
permalink: pretty

